#!/usr/bin/env python3
"""Generate one YAIF API domain YAML per business domain from a control table.

This is the "Lever 2" of scaling the API module to hundreds/thousands of
endpoints: instead of hand-copying resources/api/<domain>.yml for every domain,
keep all endpoints in one control table (tagged by domain) and let this script
emit the per-domain YAML for you. Each emitted file is byte-for-byte the same
shape as the canonical resources/api/content_domain.yml — schema + SDP pipeline +
orchestration job — so there is no new framework code and nothing magic to learn.

The control table has one row per endpoint, with these columns:

    domain, endpoint_name, path, method, params, schedule, enabled

Read it from either source (they are kept in sync):

    CSV   — quick start / local, no workspace needed:
        python scripts/generate_api_domains.py --csv examples/api/control_table.csv

    UC table — the governed runtime source of truth (see control_table.sql):
        python scripts/generate_api_domains.py \\
            --table main.config.api_endpoints --warehouse-id <id> [--profile <name>]

What it does, per domain:
  * keeps only rows where `enabled` is true
  * joins their `path` values (with `?params` appended when present) into the
    comma-separated `api_endpoints` string the fetch job already reads
  * fills the domain's job `schedule` from the `schedule` column
  * writes <out-dir>/<domain>.yml

The generator does NOT write into resources/ — it writes to a preview directory
(default: build/generated_api/) so you can review the YAML, then move the files
you want into resources/api/ and `databricks bundle deploy`.

Note on `method`/`params`: the shared fetch job (src/jobs/fetch_api_responses.py)
issues GET requests by path; `params` is appended to the path as a query string.
Non-GET rows are reported and skipped — extend the fetch contract first if you
need them.
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from pathlib import Path

# Columns expected in the control table, in order.
COLUMNS = ["domain", "endpoint_name", "path", "method", "params", "schedule", "enabled"]

# Canonical domain template. Mirrors resources/api/content_domain.yml exactly so
# generated files are indistinguishable from hand-written ones. Placeholders use
# __NAME__ markers (not $-style) so they never collide with the YAML's own
# ${var.*} / ${resources.*} bundle references.
TEMPLATE = '''\
# Domain: __DOMAIN__  (GENERATED by scripts/generate_api_domains.py — do not hand-edit)
# Source of truth: the control-table rows where domain = '__DOMAIN__'.
# Same shape as resources/api/content_domain.yml; the notebook + transformations are shared.
# To deploy: review this file, move it into resources/api/, then `databricks bundle deploy`.
# Reminder: add this pipeline's `development:` override to the dev/prod targets in
# databricks.yml (the flag belongs in the target override, never the pipeline resource).
resources:
  schemas:
    __DOMAIN___schema:
      catalog_name: ${var.catalog}
      name: yaif___DOMAIN__
      comment: "YAIF API module — __DOMAIN__ domain (bronze/silver/gold)"

  pipelines:
    __DOMAIN___ingestion:
      name: "[${bundle.target}] yaif-api-__DOMAIN__"
      catalog: ${var.catalog}
      schema: ${resources.schemas.__DOMAIN___schema.name}
      serverless: true
      photon: true
      libraries:
        - glob:
            include: ../../src/transformations/**
      configuration:
        landing_table: "${var.catalog}.${resources.schemas.__DOMAIN___schema.name}.raw_api_responses"
      continuous: false
      notifications:
        - email_recipients:
            - ${workspace.current_user.userName}
          alerts:
            - on-update-failure
            - on-update-fatal-failure
      permissions:
        - level: CAN_VIEW
          group_name: "users"

  jobs:
    __DOMAIN___fetch_and_pipeline:
      name: "[${bundle.target}] yaif-api-__DOMAIN__"
      description: "__DOMAIN__ domain: fetch APIs -> landing table -> SDP medallion"
      tasks:
        - task_key: fetch
          notebook_task:
            notebook_path: ../../src/jobs/fetch_api_responses.py
            base_parameters:
              api_connection: ${var.api_connection}
              api_endpoints: "__ENDPOINTS__"
              landing_table: "${var.catalog}.${resources.schemas.__DOMAIN___schema.name}.raw_api_responses"
              request_concurrency: ${var.request_concurrency}
          environment_key: fetch_env
        - task_key: run_pipeline
          depends_on:
            - task_key: fetch
          pipeline_task:
            pipeline_id: ${resources.pipelines.__DOMAIN___ingestion.id}
      environments:
        - environment_key: fetch_env
          spec:
            client: "2"
            dependencies:
              - "tenacity>=8.2.0"
              # Floor must exceed the serverless-preinstalled SDK, or pip skips the
              # upgrade and serving_endpoints.http_request() doesn't exist.
              - "databricks-sdk>=0.50.0"
__SCHEDULE_BLOCK__      queue:
        enabled: true
      email_notifications:
        on_failure:
          - ${workspace.current_user.userName}
'''


def _truthy(value) -> bool:
    """Interpret a control-table `enabled` cell as a boolean."""
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "t", "1", "yes", "y"}


def read_csv(path: str) -> list[dict]:
    """Read the control table from a CSV file (stdlib only — no workspace needed)."""
    with open(path, newline="", encoding="utf-8") as fh:
        return [dict(row) for row in csv.DictReader(fh)]


def read_table(fqn: str, warehouse_id: str, profile: str | None) -> list[dict]:
    """Read the control table from a Unity Catalog table via the Databricks SDK.

    Uses the standard CLI auth (profile / env vars), so no credentials live here.
    """
    if profile:
        os.environ["DATABRICKS_CONFIG_PROFILE"] = profile
    try:
        from databricks.sdk import WorkspaceClient
        from databricks.sdk.service.sql import StatementState
    except ImportError:
        sys.exit("ERROR: --table needs the Databricks SDK. Run: pip install databricks-sdk")

    cols = ", ".join(COLUMNS)
    resp = WorkspaceClient().statement_execution.execute_statement(
        warehouse_id=warehouse_id,
        statement=f"SELECT {cols} FROM {fqn}",
        wait_timeout="50s",
    )
    if resp.status.state != StatementState.SUCCEEDED:
        sys.exit(f"ERROR: query failed: {resp.status.state} {resp.status.error}")
    data = resp.result.data_array if resp.result else []
    return [dict(zip(COLUMNS, row)) for row in data]


def build_domains(rows: list[dict]) -> tuple[dict, dict]:
    """Group enabled rows by domain. Returns (domains, stats).

    domains[name] = {"endpoints": ["/posts", "/comments?postId=1", ...], "schedule": "<cron>"}
    """
    domains: dict[str, dict] = {}
    skipped_disabled = 0
    skipped_method = 0

    for row in rows:
        domain = (row.get("domain") or "").strip()
        path = (row.get("path") or "").strip()
        if not domain or not path:
            continue
        if not _truthy(row.get("enabled")):
            skipped_disabled += 1
            continue

        method = (row.get("method") or "GET").strip().upper()
        if method != "GET":
            print(f"  ! skipping {domain} {path}: method={method} (fetch job is GET-only)")
            skipped_method += 1
            continue

        params = (row.get("params") or "").strip()
        endpoint = f"{path}?{params}" if params else path

        schedule = (row.get("schedule") or "").strip()
        entry = domains.setdefault(domain, {"endpoints": [], "schedule": ""})
        entry["endpoints"].append(endpoint)
        if schedule:
            if entry["schedule"] and entry["schedule"] != schedule:
                print(
                    f"  ! domain '{domain}' has differing schedules; using the first "
                    f"('{entry['schedule']}'). A job has one schedule — split the domain "
                    f"if SLAs differ."
                )
            elif not entry["schedule"]:
                entry["schedule"] = schedule

    stats = {
        "rows": len(rows),
        "enabled_endpoints": sum(len(d["endpoints"]) for d in domains.values()),
        "domains": len(domains),
        "skipped_disabled": skipped_disabled,
        "skipped_method": skipped_method,
    }
    return domains, stats


def render(domain: str, endpoints: list[str], schedule: str) -> str:
    """Render one domain's YAML from the canonical template."""
    if schedule:
        schedule_block = (
            "      schedule:\n"
            f'        quartz_cron_expression: "{schedule}"\n'
            '        timezone_id: "UTC"\n'
        )
    else:
        schedule_block = ""
    return (
        TEMPLATE
        .replace("__DOMAIN__", domain)
        .replace("__ENDPOINTS__", ",".join(endpoints))
        .replace("__SCHEDULE_BLOCK__", schedule_block)
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate one YAIF API domain YAML per domain from a control table.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--csv", metavar="PATH", help="control table as a CSV file")
    source.add_argument(
        "--table", metavar="CATALOG.SCHEMA.TABLE", help="control table as a Unity Catalog table"
    )
    parser.add_argument(
        "--out-dir",
        default="build/generated_api",
        help="where to write the generated YAML (default: build/generated_api/ — a preview dir, "
        "NOT resources/). Move reviewed files into resources/api/ to deploy.",
    )
    parser.add_argument("--warehouse-id", help="SQL warehouse id (required with --table)")
    parser.add_argument("--profile", help="Databricks CLI profile to use with --table")
    args = parser.parse_args()

    if args.table and not args.warehouse_id:
        parser.error("--table requires --warehouse-id")

    if args.csv:
        print(f"Reading control table from CSV: {args.csv}")
        rows = read_csv(args.csv)
    else:
        print(f"Reading control table from UC table: {args.table}")
        rows = read_table(args.table, args.warehouse_id, args.profile)

    domains, stats = build_domains(rows)
    if not domains:
        sys.exit("ERROR: no enabled endpoints found — nothing to generate.")

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for domain in sorted(domains):
        entry = domains[domain]
        out_path = out_dir / f"{domain}.yml"
        out_path.write_text(render(domain, entry["endpoints"], entry["schedule"]))
        print(f"  wrote {out_path}  ({len(entry['endpoints'])} endpoints)")

    print(
        f"\nDone: read {stats['enabled_endpoints']} enabled endpoints across "
        f"{stats['domains']} domains -> wrote {stats['domains']} YAML files to {out_dir}/"
    )
    if stats["skipped_disabled"]:
        print(f"  ({stats['skipped_disabled']} disabled row(s) skipped)")
    if stats["skipped_method"]:
        print(f"  ({stats['skipped_method']} non-GET row(s) skipped)")
    print("Next: review the files, move the ones you want into resources/api/, then "
          "`databricks bundle deploy`.")


if __name__ == "__main__":
    main()
