#!/usr/bin/env python3
"""Generate one YAIF API domain YAML per business domain from a control table.

This is the "Lever 2" of scaling the API module to hundreds/thousands of
endpoints: instead of hand-copying resources/api/<domain>.yml for every domain,
keep all endpoints in one control table (tagged by domain) and let this script
emit the per-domain YAML for you. Each emitted file is byte-for-byte the same
shape as the canonical resources/api/content_domain.yml — schema + SDP pipeline +
orchestration job — so there is no new framework code and nothing magic to learn.

The control table has one row per endpoint, with these columns:

    domain, endpoint_name, path, method, params, schedule, enabled,
    body, auth_mode, silver_shape

`body`/`auth_mode`/`silver_shape` are OPTIONAL trailing columns — older 7-column
tables still parse (the generator fills them via dict.get with safe defaults). The
last three are read but default to GET / connection / records, so a table of plain
GET rows generates byte-for-byte the same YAML as before.

Read it from either source (they are kept in sync):

    CSV   — quick start / local, no workspace needed:
        python scripts/generate_api_domains.py --csv examples/api/control_table.csv

    UC table — the governed runtime source of truth (see control_table.sql):
        python scripts/generate_api_domains.py \\
            --table main.config.api_endpoints --warehouse-id <id> [--profile <name>]

What it does, per domain:
  * keeps only rows where `enabled` is true
  * collects each row as a request spec {path(+?params), method, body?}
  * when EVERY spec is a GET with no body, emits the comma-separated `api_endpoints`
    CSV string the fetch job has always read (byte-for-byte unchanged); when any spec
    is non-GET or carries a body, emits `api_endpoints_json` (a JSON array of specs)
  * threads per-domain `auth_mode` (connection | basic_secret) and `silver_shape`
    (records | document) — both default-safe and omitted from the YAML when default
  * fills the domain's job `schedule` from the `schedule` column
  * writes <out-dir>/<domain>.yml

The generator does NOT write into resources/ — it writes to a preview directory
(default: build/generated_api/) so you can review the YAML, then move the files
you want into resources/api/ and `databricks bundle deploy`.

Note on auth: `auth_mode: basic_secret` needs an `api_base_url` and a secret scope
(see resources/api/echo_post_demo.yml / examples/api/epm_domain.yml). The generator
emits a TODO placeholder for those so you fill them in (never commit real hosts/creds).
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from pathlib import Path

# Columns expected in the control table, in order. The first 7 are required; `body`,
# `auth_mode`, and `silver_shape` are optional trailing columns (read via dict.get with
# safe defaults), so a 7-column table still parses.
COLUMNS = [
    "domain", "endpoint_name", "path", "method", "params", "schedule", "enabled",
    "body", "auth_mode", "silver_shape",
]

# Canonical domain template. Mirrors resources/api/content_domain.yml exactly so
# generated files are indistinguishable from hand-written ones. Placeholders use
# __NAME__ markers (not $-style) so they never collide with the YAML's own
# ${var.*} / ${resources.*} bundle references.
TEMPLATE = '''\
# Domain: __DOMAIN__  (GENERATED by scripts/generate_api_domains.py — do not hand-edit)
# Source of truth: the control-table rows where domain = '__DOMAIN__'.
# Same shape as resources/api/content_domain.yml; the notebook + transformations are shared.
# To deploy: review this file, move it into resources/api/, then `databricks bundle deploy`.
# No databricks.yml edits needed: the target mode (development/production) sets each
# pipeline's `development` flag automatically — onboarding a domain is a pure file copy.
resources:
  schemas:
    __DOMAIN___schema:
      catalog_name: ${var.catalog}
      name: yaif___DOMAIN__
      comment: "YAIF API module — __DOMAIN__ domain (bronze/silver/gold)"

  pipelines:
    __DOMAIN___ingestion:
      name: "[${bundle.target}] yaif-api-__DOMAIN__"
      catalog: ${var.catalog}
      schema: ${resources.schemas.__DOMAIN___schema.name}
      serverless: true
      photon: true
      libraries:
        - glob:
            include: ../../src/transformations/**
      configuration:
        landing_table: "${var.catalog}.${resources.schemas.__DOMAIN___schema.name}.raw_api_responses"
__SILVER_SHAPE_CONFIG__      continuous: false
      notifications:
        - email_recipients:
            - ${workspace.current_user.userName}
          alerts:
            - on-update-failure
            - on-update-fatal-failure
      permissions:
        - level: CAN_VIEW
          group_name: ${var.viewers_group}

  jobs:
    __DOMAIN___fetch_and_pipeline:
      name: "[${bundle.target}] yaif-api-__DOMAIN__"
      description: "__DOMAIN__ domain: fetch APIs -> landing table -> SDP medallion"
      tasks:
        - task_key: fetch
          notebook_task:
            notebook_path: ../../src/jobs/fetch_api_responses.py
            base_parameters:
              api_connection: ${var.api_connection}
__ENDPOINTS_BLOCK____AUTH_BLOCK__              landing_table: "${var.catalog}.${resources.schemas.__DOMAIN___schema.name}.raw_api_responses"
              request_concurrency: ${var.request_concurrency}
          environment_key: fetch_env
          # Retry infra-level failures (e.g. environment build) and bound runtime — the
          # in-code tenacity retries only cover HTTP calls, not task setup.
          max_retries: 2
          timeout_seconds: 3600
        - task_key: run_pipeline
          depends_on:
            - task_key: fetch
          pipeline_task:
            pipeline_id: ${resources.pipelines.__DOMAIN___ingestion.id}
      environments:
        - environment_key: fetch_env
          spec:
            client: "2"
            dependencies:
              - "tenacity>=8.2.0"
              # Floor must exceed the serverless-preinstalled SDK, or pip skips the
              # upgrade and serving_endpoints.http_request() doesn't exist.
              - "databricks-sdk>=0.50.0"
__SCHEDULE_BLOCK__      queue:
        enabled: true
      email_notifications:
        on_failure:
          - ${workspace.current_user.userName}
      permissions:
        - level: CAN_VIEW
          group_name: ${var.viewers_group}
'''


def _truthy(value) -> bool:
    """Interpret a control-table `enabled` cell as a boolean."""
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "t", "1", "yes", "y"}


def read_csv(path: str) -> list[dict]:
    """Read the control table from a CSV file (stdlib only — no workspace needed)."""
    with open(path, newline="", encoding="utf-8") as fh:
        return [dict(row) for row in csv.DictReader(fh)]


def read_table(fqn: str, warehouse_id: str, profile: str | None) -> list[dict]:
    """Read the control table from a Unity Catalog table via the Databricks SDK.

    Uses the standard CLI auth (profile / env vars), so no credentials live here.
    """
    if profile:
        os.environ["DATABRICKS_CONFIG_PROFILE"] = profile
    try:
        from databricks.sdk import WorkspaceClient
        from databricks.sdk.service.sql import StatementState
    except ImportError:
        sys.exit("ERROR: --table needs the Databricks SDK. Run: pip install databricks-sdk")

    # SELECT * so older 7-column tables (without body/auth_mode/silver_shape) still work;
    # map by the actual returned column names and let build_domains apply defaults.
    client = WorkspaceClient()
    resp = client.statement_execution.execute_statement(
        warehouse_id=warehouse_id,
        statement=f"SELECT * FROM {fqn}",
        wait_timeout="50s",
    )
    if resp.status.state != StatementState.SUCCEEDED:
        sys.exit(f"ERROR: query failed: {resp.status.state} {resp.status.error}")
    col_names = [c.name for c in resp.manifest.schema.columns] if resp.manifest else COLUMNS
    data = resp.result.data_array if resp.result else []
    return [dict(zip(col_names, row)) for row in data]


def _resolve_domain_setting(entry: dict, key: str, value: str, domain: str, default: str) -> None:
    """Set a per-domain setting (auth_mode / silver_shape), warning on a conflict.

    Auth/shape are per-domain, but live on each endpoint row for table simplicity. The
    first non-default value wins; a differing later value is a config error worth flagging.
    """
    value = (value or "").strip().lower()
    if not value or value == default:
        return
    if entry[key] not in (default, value):
        print(
            f"  ! domain '{domain}' has conflicting {key} "
            f"('{entry[key]}' vs '{value}'); using the first. {key} is per-domain — "
            f"split the domain if they must differ."
        )
        return
    entry[key] = value


def build_domains(rows: list[dict]) -> tuple[dict, dict]:
    """Group enabled rows by domain. Returns (domains, stats).

    domains[name] = {
        "endpoints": [{"path": "/posts", "method": "GET"}, ...],  # request specs
        "schedule": "<cron>", "auth_mode": "connection", "silver_shape": "records",
    }
    """
    domains: dict[str, dict] = {}
    skipped_disabled = 0
    non_get_endpoints = 0

    for row in rows:
        domain = (row.get("domain") or "").strip()
        path = (row.get("path") or "").strip()
        if not domain or not path:
            continue
        if not _truthy(row.get("enabled")):
            skipped_disabled += 1
            continue

        method = (row.get("method") or "GET").strip().upper() or "GET"
        params = (row.get("params") or "").strip()
        full_path = f"{path}?{params}" if params else path
        body_raw = (row.get("body") or "").strip()

        spec: dict = {"path": full_path, "method": method}
        if body_raw:
            try:
                spec["body"] = json.loads(body_raw)
            except json.JSONDecodeError:
                # Keep the raw string body (the fetch job sends it as-is).
                spec["body"] = body_raw
        if method != "GET" or body_raw:
            non_get_endpoints += 1

        entry = domains.setdefault(
            domain,
            {"endpoints": [], "schedule": "", "auth_mode": "connection", "silver_shape": "records"},
        )
        entry["endpoints"].append(spec)

        schedule = (row.get("schedule") or "").strip()
        if schedule:
            if entry["schedule"] and entry["schedule"] != schedule:
                print(
                    f"  ! domain '{domain}' has differing schedules; using the first "
                    f"('{entry['schedule']}'). A job has one schedule — split the domain "
                    f"if SLAs differ."
                )
            elif not entry["schedule"]:
                entry["schedule"] = schedule

        _resolve_domain_setting(entry, "auth_mode", row.get("auth_mode", ""), domain, "connection")
        _resolve_domain_setting(entry, "silver_shape", row.get("silver_shape", ""), domain, "records")

    stats = {
        "rows": len(rows),
        "enabled_endpoints": sum(len(d["endpoints"]) for d in domains.values()),
        "domains": len(domains),
        "skipped_disabled": skipped_disabled,
        "non_get_endpoints": non_get_endpoints,
    }
    return domains, stats


def _endpoints_block(endpoints: list[dict]) -> str:
    """Render the fetch endpoints base_parameter.

    GET-only with no body => the legacy `api_endpoints` CSV line (byte-for-byte
    identical to the historical generator output, so generated_sample/blog.yml is
    preserved). Otherwise => an `api_endpoints_json` block-scalar holding the specs.
    """
    all_get_no_body = all(
        ep.get("method", "GET").upper() == "GET" and "body" not in ep for ep in endpoints
    )
    if all_get_no_body:
        csv = ",".join(ep["path"] for ep in endpoints)
        return f'              api_endpoints: "{csv}"\n'
    # Pretty-print the JSON array as a YAML block scalar (|), indented under the key.
    pretty = json.dumps(endpoints, indent=2)
    indented = "\n".join("                " + line for line in pretty.splitlines())
    return f"              api_endpoints_json: |\n{indented}\n"


def _auth_block(auth_mode: str) -> str:
    """Render the auth base_parameters. Empty for the default connection mode."""
    if auth_mode != "basic_secret":
        return ""
    return (
        '              auth_mode: "basic_secret"\n'
        "              # TODO: fill these in — never commit a real host or credentials.\n"
        "              # api_base_url MUST be a scheme+host (e.g. https://host); secrets stay in a UC scope.\n"
        "              api_base_url: ${var.api_base_url}\n"
        "              secret_scope: ${var.api_secret_scope}\n"
        '              secret_key_username: "username"\n'
        '              secret_key_password: "password"\n'
    )


def _silver_shape_config(silver_shape: str) -> str:
    """Render the pipeline `silver_shape` configuration line. Empty for default records."""
    if silver_shape != "document":
        return ""
    return '        silver_shape: "document"\n'


def render(domain: str, entry: dict) -> str:
    """Render one domain's YAML from the canonical template."""
    schedule = entry["schedule"]
    if schedule:
        schedule_block = (
            "      schedule:\n"
            f'        quartz_cron_expression: "{schedule}"\n'
            '        timezone_id: "UTC"\n'
        )
    else:
        schedule_block = ""
    return (
        TEMPLATE
        .replace("__DOMAIN__", domain)
        .replace("__ENDPOINTS_BLOCK__", _endpoints_block(entry["endpoints"]))
        .replace("__AUTH_BLOCK__", _auth_block(entry["auth_mode"]))
        .replace("__SILVER_SHAPE_CONFIG__", _silver_shape_config(entry["silver_shape"]))
        .replace("__SCHEDULE_BLOCK__", schedule_block)
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate one YAIF API domain YAML per domain from a control table.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--csv", metavar="PATH", help="control table as a CSV file")
    source.add_argument(
        "--table", metavar="CATALOG.SCHEMA.TABLE", help="control table as a Unity Catalog table"
    )
    parser.add_argument(
        "--out-dir",
        default="build/generated_api",
        help="where to write the generated YAML (default: build/generated_api/ — a preview dir, "
        "NOT resources/). Move reviewed files into resources/api/ to deploy.",
    )
    parser.add_argument("--warehouse-id", help="SQL warehouse id (required with --table)")
    parser.add_argument("--profile", help="Databricks CLI profile to use with --table")
    args = parser.parse_args()

    if args.table and not args.warehouse_id:
        parser.error("--table requires --warehouse-id")

    if args.csv:
        print(f"Reading control table from CSV: {args.csv}")
        rows = read_csv(args.csv)
    else:
        print(f"Reading control table from UC table: {args.table}")
        rows = read_table(args.table, args.warehouse_id, args.profile)

    domains, stats = build_domains(rows)
    if not domains:
        sys.exit("ERROR: no enabled endpoints found — nothing to generate.")

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for domain in sorted(domains):
        entry = domains[domain]
        out_path = out_dir / f"{domain}.yml"
        out_path.write_text(render(domain, entry))
        print(f"  wrote {out_path}  ({len(entry['endpoints'])} endpoints)")

    print(
        f"\nDone: read {stats['enabled_endpoints']} enabled endpoints across "
        f"{stats['domains']} domains -> wrote {stats['domains']} YAML files to {out_dir}/"
    )
    if stats["skipped_disabled"]:
        print(f"  ({stats['skipped_disabled']} disabled row(s) skipped)")
    if stats["non_get_endpoints"]:
        print(
            f"  ({stats['non_get_endpoints']} non-GET / body endpoint(s) emitted as "
            "api_endpoints_json)"
        )
    print("Next: review the files, move the ones you want into resources/api/, then "
          "`databricks bundle deploy`.")


if __name__ == "__main__":
    main()
